# BurkAR 1.0.1
# Written by CJ Burkey
extraDebugInConsole: true
saveAutomatically: true
autoSaveTimeInSeconds: 300
tickTimeUpdate: 5
langPrefix: '&6[&aBurkAR&6]&r '
langTimeFormat: '%d:%02d:%02d'
langUsage: '&4Usage: /bar <username>'
langLackPermOthers: '&4You don''t have permission to view other players'' times.'
langLackPermInfo: '&4You don''t have permission to view info about BurkAR.'
langLackPerm: '&4You don''t have permission to use BurkAR.'
langErr: '&4There was an error while retrieving your play time.'
langSelf: '&2You''ve spent %s on the server.  Nice!'
langOther: '&2''%s'' has spent %s on the server.'
langInfo: '&2BurkAR version: %s'